spring:
  application:
    name: kotlin
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:dalaran}
  datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8083




