spring:
  application:
    name: kotlin
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
    elasticsearch:
      cluster-name: elasticsearch_yaojiafeng
  datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
  redis:
      database: 0
      host: localhost
      port: 6379


server:
  port: 8083





